main page
js-tasks-ru/htmlcss-20220919_vs-oko pull request #2
Opened 2022-09-25 15:28 UTC by Dormeh

2022-09-25 15:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-27 08:26 UTC, GSemikozov requested changes

2022-09-27 08:26 UTC, GSemikozov commented on components/footer/footer.css
> +    min-width: 640px;
max-width

2022-09-27 08:26 UTC, GSemikozov commented on components/footer/footer.css
> +    max-width: 75%;
удалим

2022-09-27 08:26 UTC, GSemikozov commented on components/footer/footer.css
> +    position: absolute;
абсолютом не надо - удалим

2022-09-27 20:19 UTC, GSemikozov requested changes

2022-09-27 20:19 UTC, GSemikozov commented on components/footer/footer.css
> +    min-width: 640px;
здесь max-width

2022-09-28 20:51 UTC, GSemikozov approved these changes

2022-09-28 20:51 UTC, merged