button element
js-tasks-ru/htmlcss-20220919_vs-oko pull request #3
Opened 2022-09-26 11:42 UTC by Dormeh

2022-09-26 11:42 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-27 08:29 UTC, GSemikozov requested changes

2022-09-27 08:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 0;
паддинги как раз лучше указать общие для всех кнопок, как в макете

2022-09-27 08:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font: inherit;
не надо наследоваться, лучше явно прописать (мы не хотим чтобы в зависимости от контекста шрифт кнопки менялся)

2022-09-27 08:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
фиксировать ширину не нужно, пусть зависит от внутреннего содержимого

2022-09-27 08:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    color: inherit;
не хватает line-height + font-size

2022-09-27 08:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__title {
лишний элемент, кнопки у нас простые, в них будет только текст

2022-09-27 08:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    margin: 16px;
на уровне блока марджины не задаем, можно удалить

2022-09-27 08:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    transition: opacity 200ms ease-in-out, background 200ms ease-in-out;
если это общий транзишн хотя бы для 2 типов кнопок - тогда лучше перенести в .button

2022-09-27 08:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_secondary {
ниже аналогично комментам по primary

2022-09-27 13:29 UTC, Dormeh commented on 03-lection1/01-button/button.css
> +.button__title {
меня смутил тот факт, что при disabled opacity: 0.5 не наследуется текстовым узлом
поэтому добавил span

2022-09-27 13:31 UTC, Dormeh commented on 03-lection1/01-button/button.css
> +    transition: opacity 200ms ease-in-out, background 200ms ease-in-out;
я так и сделал в начале, но в итоге перенес в модификаторы так как именно там стилистика прописана

2022-09-27 14:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-27 20:21 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__title {
ответил в чате

2022-09-27 20:21 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    transition: opacity 200ms ease-in-out, background 200ms ease-in-out;
в модификаторах описывает то специфическое, что отличает 1 тип от другого - в данном случае, transition совпадают, а значит это нечто общее, а не особенное, поэтому можно задать на уровне .button

2022-09-27 20:23 UTC, GSemikozov requested changes

2022-09-27 20:23 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +<button class="button button_primary">Primary</button>
в разметке еще желательно добавить эти же кнопки но с атрибутом disabled

2022-09-27 21:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-28 11:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-28 20:50 UTC, GSemikozov requested changes

2022-09-28 20:50 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    margin: 16px;
марджины на уровне блока не задаем

2022-09-30 08:17 UTC, GSemikozov approved these changes

2022-09-30 08:18 UTC, merged