задача accordion
js-tasks-ru/htmlcss-20220919_vs-oko pull request #4
Opened 2022-09-28 18:14 UTC by Dormeh

2022-09-28 18:14 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-28 20:54 UTC, GSemikozov requested changes

2022-09-28 20:54 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin: 0 49px 32px 32px;
вместо однотипных марджинов на уровне .accordion__text и .accordion__summary лучше задать 1 раз на уровне accordion__card, причем паддинги (это ведь внутренние отступы)

2022-09-28 20:54 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin: 24px 28px 24px 32px;;
лишняя `;`

2022-09-28 20:54 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__card[open] .accordion__marker {
роме того при .accordion__card[open] меняется еще и отступ снизу у .accordion__card

2022-09-28 20:54 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin: 0 0 0 490px;
ого)
нет, на самом деле теперь мы знаем технику которая позволит разместить иконку справа (и это флексбокс)

2022-09-29 09:49 UTC, Dormeh commented on 03-lection1/02-accordion/accordion.css
> +    margin: 0 0 0 490px;
это задание было до изучения данной техники так что все по в рамках курса)

2022-09-29 14:26 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-29 14:27 UTC, Dormeh commented
изменил позиционирование на display: flex
поменял svg
добавил padding accordion__card
поменял margin на padding у элементов
добавил анимацию открытия

2022-09-29 15:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-29 20:32 UTC, GSemikozov requested changes

2022-09-29 20:32 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    max-width: 1110px;
лишнее, удалим

2022-09-29 20:32 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    display: inline-block;
в случае с таким сложным компонентом как аккордион здесь все-таки лучше оставить его блочным

2022-09-29 20:32 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    height: 72px;
фиксировать высоту не надо (что, если контента будет больше чем влезет по высоте?)

2022-09-29 20:32 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    height: 154px;
лишнее

2022-09-29 23:14 UTC, Dormeh commented on 03-lection1/02-accordion/accordion.css
> +    height: 72px;
> фиксировать высоту не надо (что, если контента будет больше чем влезет по высоте?)

это только для анимации сделал
иначе она не будет работать

2022-09-29 23:15 UTC, Dormeh commented on 03-lection1/02-accordion/accordion.css
> +    height: 154px;
это тоже часть анимации

2022-09-29 23:26 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-29 23:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-30 08:17 UTC, GSemikozov approved these changes

2022-09-30 08:17 UTC, merged