skeleton element
js-tasks-ru/htmlcss-20220919_vs-oko pull request #7
Opened 2022-10-02 17:33 UTC by Dormeh

2022-10-02 17:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-02 17:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-02 20:39 UTC, GSemikozov requested changes

2022-10-02 20:39 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.line-container {
.skeleton__line-container

2022-10-03 10:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-03 10:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-03 18:36 UTC, GSemikozov approved these changes

2022-10-03 18:36 UTC, merged